name: Build libsodium

on:
  push:
    paths:
      - 'libsodium/**'
      - '.github/workflows/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: ubuntu-latest
          arch: amd64
          triplet: x86_64-unknown-linux-gnu
        - os: ubuntu-latest
          arch: arm64
          triplet: aarch64-unknown-linux-gnu
        - os: macos-latest
          arch: amd64
          triplet: x86_64-apple-darwin
        - os: macos-latest
          arch: arm64
          triplet: arm64-apple-darwin
        - os: windows-latest
          arch: amd64
          triplet: x86_64-w64-mingw32

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true   # pull in libsodium submodule

      - name: install build deps (linux)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y build-essential autoconf automake libtool

      - name: install build deps (macos)
        if: runner.os == 'macOS'
        run: brew install autoconf automake libtool

      - name: install build deps (windows)
        if: runner.os == 'Windows'
        uses: lukka/get-cmake@latest

      - name: configure & build (linux)
        if: runner.os == 'Linux'
        run: |
          cd libsodium
          ./autogen.sh || true
          ./configure --disable-shared --enable-static --host=${{ matrix.triplet }} --prefix=$PWD/dist
          make -j$(nproc || sysctl -n hw.ncpu)
          make install

      - name: configure & build (macos)
        if: runner.os == 'macOS'
        run: |
          export CFLAGS="-mmacosx-version-min=13.0"
          export LDFLAGS="-mmacosx-version-min=13.0"
          cd libsodium
          ./autogen.sh || true
          ./configure --disable-shared --enable-static --host=${{ matrix.triplet }} --prefix=$PWD/dist
          make -j$(nproc || sysctl -n hw.ncpu)
          make install

      - name: configure & build (Windows)
        if: runner.os == 'Windows'
        run: |
          cd libsodium
          cmake -S . -B build -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=dist
          cmake --build build --config Release --target install

      - name: copy artifact
        run: |
          mkdir -p prebuilt/${{ matrix.triplet }}
          if [ "${{ runner.os }}" == "Windows" ]; then
            cp libsodium/dist/lib/libsodium.a prebuilt/${{ matrix.triplet }}/libsodium.lib || true
          else
            cp libsodium/dist/lib/libsodium.a prebuilt/${{ matrix.triplet }}/
          fi

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update libsodium prebuilt for ${{ matrix.triplet }}"
          file_pattern: prebuilt/**
